In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

plt.rcParams["figure.figsize"] = (12,6)

# NumPy

**Задача 1**\
Сгенерировать массив из случайных положительных чисел произвольной длины. Вывести элементы, которые больше среднего арифметического.

In [5]:
import random

size = 15
min_value = 0
max_value = 100

arr = np.array([random.randint(min_value, max_value) for _ in range(size)])
arr

array([29,  5, 33, 54, 45, 26, 42,  8, 11, 49, 42, 83, 88, 83, 40])

In [6]:
mean_value = np.mean(arr)  #находим среднее арифметическое значение
print(f'Среднее арифметическое значение равно {mean_value}')

Среднее арифметическое значение равно 42.53333333333333


In [7]:
more_than_mean = arr[arr > mean_value]  #выводим элементы которые больше среднего арифметического
more_than_mean

array([54, 45, 49, 83, 88, 83])

**Задача 2**\
Сгенерировать массив из 20 случайных элементов, элементы которого лежат в интервале [0, 10].
+ Определить количество элементов, отличающихся от минимального на 5.
+ Найти среднее арифметическое всех четных элементов массива, стоящих на нечетных местах.

In [9]:
size = 20  
min_value = 0
max_value = 10 

arr1 = np.array([random.randint(min_value, max_value) for _ in range(size)])
arr1

array([ 8,  8,  5,  4,  8,  9, 10,  6,  4,  6,  6,  1, 10,  0,  5,  3,  5,
        2,  3,  8])

In [10]:
min_arr1 = np.min(arr1)
count_of_numbers_5 = np.sum(np.abs(arr1 - min_arr1) == 5)
print(f'Минимальное значение составляет: {min_arr1}')
print(f'Количество элементов, отличающихся от минимального на 5: {count_of_numbers_5}')

Минимальное значение составляет: 0
Количество элементов, отличающихся от минимального на 5: 3


In [11]:
elements_in_odd_place = arr1[1::2]  #находим элементы на нечетных местах
elements_in_odd_place

array([8, 4, 9, 6, 6, 1, 0, 3, 2, 8])

In [12]:
even_elements_in_odd_place = elements_in_odd_place[elements_in_odd_place % 2 == 0]
mean_elements = np.mean(even_elements_in_odd_place) if len(even_elements_in_odd_place) > 0 else None
print(f'Все четные элементы массива на нечетных местах: {even_elements_in_odd_place}')
print(f'Среднее арифметическое всех четных элементов массива, стоящих на нечетных местах равно {mean_elements}')

Все четные элементы массива на нечетных местах: [8 4 6 6 0 2 8]
Среднее арифметическое всех четных элементов массива, стоящих на нечетных местах равно 4.857142857142857


**Задача 3**\
Сгенерировать матрицу A размером 5 на 5, элементы которой лежат в интервале [1, 10].
+ Возвести в квадрат максимальный элемент матрицы.
+ Все четные числа заменить на 0.

In [14]:
min_value = 1
max_value = 10

arr2 = np.random.randint(min_value, max_value, size=(5, 5))
arr2

array([[6, 2, 4, 9, 1],
       [5, 9, 1, 2, 5],
       [7, 8, 7, 2, 2],
       [6, 1, 7, 9, 4],
       [2, 4, 5, 3, 7]])

In [15]:
max_element = np.max(arr2)
max_element_2 = max_element ** 2
print(f'Квадрат максимального элемента матрицы: {max_element_2}')

Квадрат максимального элемента матрицы: 81


In [16]:
arr2[arr2 % 2 == 0] = 0   #заменяем все четные элементы матрицы на 0
arr2

array([[0, 0, 0, 9, 1],
       [5, 9, 1, 0, 5],
       [7, 0, 7, 0, 0],
       [0, 1, 7, 9, 0],
       [0, 0, 5, 3, 7]])

**Задача 4**\
Сгенерировать матрицу B размером 5 на 5, элементы которой лежат в интервале [-5, 5]. Отрицательные элементы матрицы заменить на число отрицательных элементов в строке, в которой они находятся.

In [18]:
min_value = -5
max_value = 5

B = np.random.randint(min_value, max_value, size=(5, 5))
B

array([[-3, -2, -2,  2,  3],
       [-2, -4,  2, -5,  2],
       [-5,  1,  2, -5, -1],
       [-1,  4,  0, -5, -1],
       [ 3,  2,  4, -2, -4]])

In [19]:
for i in range(B.shape[0]):
    B[i][B[i] < 0] = np.sum(B[i] < 0)
B

array([[3, 3, 3, 2, 3],
       [3, 3, 2, 3, 2],
       [3, 1, 2, 3, 3],
       [3, 4, 0, 3, 3],
       [3, 2, 4, 2, 2]])

# Pandas

In [21]:
df = pd.read_csv("https://raw.githubusercontent.com/rolandmueller/titanic/main/titanic3.csv")

In [22]:
df.sample(4)

pclass  survived                                             name  \
1206       3         0                            Skoog, Master. Harald   
2          1         0                     Allison, Miss. Helen Loraine   
998        3         0                             Matinoff, Mr. Nicola   
160        1         1  Hippach, Mrs. Louis Albert (Ida Sophia Fischer)   

         sex   age  sibsp  parch  ticket      fare    cabin embarked boat  \
1206    male   4.0      3      2  347088   27.9000      NaN        S  NaN   
2     female   2.0      1      2  113781  151.5500  C22 C26        S  NaN   
998     male   NaN      0      0  349255    7.8958      NaN        C  NaN   
160   female  44.0      0      1  111361   57.9792      B18        C    4   

      body                        home.dest  
1206   NaN                              NaN  
2      NaN  Montreal, PQ / Chesterville, ON  
998    NaN                              NaN  
160    NaN                      Chicago, IL

**Задание 1**
+ Какой была максимальная цена билета? Медиана?
+ Какова доля выживших?
+ Сколько мужчин / женщин находилось на борту?

In [24]:
print(f'Максимальная цена билета равна {df["fare"].max()}')
print(f'Медианная цена билета равна {df["fare"].median()}')
print(f'Доля выживших составляет {(df["survived"].sum() / len(df)):.4f}')
print('На борту находилось', len(df[df['sex'] == 'male']), 'мужчин и', len(df[df['sex'] == 'female']), 'женщин')

Максимальная цена билета равна 512.3292
Медианная цена билета равна 14.4542
Доля выживших составляет 0.3820
На борту находилось 843 мужчин и 466 женщин


**Задание 2**
+ Выведите распределение переменной __pclass__ для мужчин и женщин.
    + Сколько мужчин было в первом классе?
    + Сколько женщин было в третьем классе?
      
+ Создайте новый признак __age_group__, который равен:
    + 1, если пассажир был моложе 30 лет;
    + 2, если пассажиру было от 30 до 60 лет;
    + 3, если пассажир был старше 60 лет.

In [26]:
pclass_distribution = df.groupby('pclass')['sex'].value_counts().unstack() #распределение переменной pclass для мужчин и женщин
pclass_distribution

sex     female  male
pclass              
1          144   179
2          106   171
3          216   493

In [27]:
men_in_the_first_class  = df[(df['pclass'] == 1) & (df['sex'] == 'male')].shape[0]
women_in_the_first_class = df[(df['pclass'] == 3) & (df['sex'] == 'female')].shape[0]
print('В первом классе было', men_in_the_first_class, 'мужчин')
print('В третьем классе было', women_in_the_first_class, 'женщин')

В первом классе было 179 мужчин
В третьем классе было 216 женщин


In [28]:
df['age_group'] = df['age'].apply(lambda x: 1 if x < 30 else (3 if x > 60 else 2))
df[['age_group','age']].sample(5)

age_group   age
1259          2  36.0
993           2   NaN
939           2  36.0
817           1  22.0
481           1  22.0

**Задание 3**\
Найдите самое популярное имя среди пассажиров:
+ мужчин;
+ женщин.

In [30]:
df['first_name'] = df['name'].str.extract(r', \w+\. ([\w-]+)') #создаем новый столбец тольско с именами
male_names = df[df['sex'] == 'male']['first_name']
female_names = df[df['sex'] == 'female']['first_name']
popular_male_name = male_names.mode().tolist()
popular_female_name = female_names.mode().tolist()
print(f'Самое популярное мужское имя {popular_male_name[0]}')
print(f'Самое популярное женское имя {popular_female_name[0]}')

Самое популярное мужское имя William
Самое популярное женское имя William


**Задание 4**
+ Выведите данные о всех пассажирах, которые сели в Cherbourg (Embarked='C') и были старше 50 лет.
+ Выведите данные о всех женщинах младше 20 и старше 50 лет.
+ Сколько пассажиров старше 70 лет было на борту?

In [32]:
cherbourg_50 = df[(df['embarked'] == 'C') & (df['age'] > 50)]
cherbourg_50

pclass  survived                                               name  \
9         1         0                            Artagaveytia, Mr. Ramon   
43        1         1    Bucknell, Mrs. William Robert (Emma Eliza Ward)   
48        1         1   Candee, Mrs. Edward (Helen Churchill Hungerford)   
50        1         1  Cardeza, Mrs. James Warburton Martinez (Charlo...   
78        1         1  Compton, Mrs. Alexander Taylor (Mary Eliza Ing...   
104       1         1                     Eustis, Miss. Elizabeth Mussey   
123       1         1                   Frolicher-Stehli, Mr. Maxmillian   
135       1         0                          Goldschmidt, Mr. George B   
136       1         1                          Gracie, Col. Archibald IV   
174       1         0                            Kent, Mr. Edward Austin   
186       1         1          Lindstrom, Mrs. Carl Johan (Sigrid Posse)   
192       1         1                               Lurette, Miss. Elise   
215       1         0                         Newell, Mr. Arthur Webster   
221       1         0                     Ostby, Mr. Engelhart Cornelius   
233       1         1      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)   
246       1         0                             Rothschild, Mr. Martin   
247       1         1     Rothschild, Mrs. Martin (Elizabeth L. Barrett)   
252       1         0                         Ryerson, Mr. Arthur Larned   
264       1         1                Simonius-Blumer, Col. Oberst Alfons   
267       1         0                            Smith, Mr. James Clinch   
276       1         0                      Spencer, Mr. William Augustus   
280       1         1                    Stengel, Mr. Charles Emil Henry   
282       1         1    Stephenson, Mrs. Walter Bertram (Martha Eustis)   
303       1         0                           Warren, Mr. Frank Manley   
304       1         1   Warren, Mrs. Frank Manley (Anna Sophia Atkinson)   
308       1         1              White, Mrs. John Stuart (Ella Holmes)   
316       1         0                        Williams, Mr. Charles Duane   

        sex   age  sibsp  parch    ticket      fare            cabin embarked  \
9      male  71.0      0      0  PC 17609   49.5042              NaN        C   
43   female  60.0      0      0     11813   76.2917              D15        C   
48   female  53.0      0      0  PC 17606   27.4458              NaN        C   
50   female  58.0      0      1  PC 17755  512.3292      B51 B53 B55        C   
78   female  64.0      0      2  PC 17756   83.1583              E45        C   
104  female  54.0      1      0     36947   78.2667              D20        C   
123    male  60.0      1      1     13567   79.2000              B41        C   
135    male  71.0      0      0  PC 17754   34.6542               A5        C   
136    male  53.0      0      0    113780   28.5000              C51        C   
174    male  58.0      0      0     11771   29.7000              B37        C   
186  female  55.0      0      0    112377   27.7208              NaN        C   
192  female  58.0      0      0  PC 17569  146.5208              B80        C   
215    male  58.0      0      2     35273  113.2750              D48        C   
221    male  65.0      0      1    113509   61.9792              B30        C   
233  female  56.0      0      1     11767   83.1583              C50        C   
246    male  55.0      1      0  PC 17603   59.4000              NaN        C   
247  female  54.0      1      0  PC 17603   59.4000              NaN        C   
252    male  61.0      1      3  PC 17608  262.3750  B57 B59 B63 B66        C   
264    male  56.0      0      0     13213   35.5000              A26        C   
267    male  56.0      0      0     17764   30.6958               A7        C   
276    male  57.0      1      0  PC 17569  146.5208              B78        C   
280    male  54.0      1      0     11778   55.4417             C116        C   
282  female  

Всего таких пассажиров оказалось 27

In [34]:
women_for_4th_task = df[(df['sex'] == 'female') & (df['age'] > 50) | (df['age'] < 20)]
women_for_4th_task

pclass  survived                                               name  \
1          1         1                     Allison, Master. Hudson Trevor   
2          1         0                       Allison, Miss. Helen Loraine   
6          1         1                  Andrews, Miss. Kornelia Theodosia   
8          1         1      Appleton, Mrs. Edward Dale (Charlotte Lamson)   
11         1         1  Astor, Mrs. John Jacob (Madeleine Talmadge Force)   
...      ...       ...                                                ...   
1275       3         0                    Vander Planke, Mr. Leo Edmondus   
1279       3         0               Vestrom, Miss. Hulda Amanda Adolfina   
1288       3         0                          Wiklund, Mr. Jakob Alfred   
1300       3         1            Yasbeck, Mrs. Antoni (Selini Alexander)   
1304       3         0                               Zabour, Miss. Hileni   

         sex      age  sibsp  parch    ticket      fare    cabin embarked  \
1       male   0.9167      1      2    113781  151.5500  C22 C26        S   
2     female   2.0000      1      2    113781  151.5500  C22 C26        S   
6     female  63.0000      1      0     13502   77.9583       D7        S   
8     female  53.0000      2      0     11769   51.4792     C101        S   
11    female  18.0000      1      0  PC 17757  227.5250  C62 C64        C   
...      ...      ...    ...    ...       ...       ...      ...      ...   
1275    male  16.0000      2      0    345764   18.0000      NaN        S   
1279  female  14.0000      0      0    350406    7.8542      NaN        S   
1288    male  18.0000      1      0   3101267    6.4958      NaN        S   
1300  female  15.0000      1      0      2659   14.4542      NaN        C   
1304  female  14.5000      1      0      2665   14.4542      NaN        C   

     boat   body                        home.dest  age_group first_name  
1      11    NaN  Montreal, PQ / Chesterville, ON          1     Hudson  
2     NaN    NaN  Montreal, PQ / Chesterville, ON          1      Helen  
6      10    NaN                       Hudson, NY          3   Kornelia  
8       D    NaN              Bayside, Queens, NY          2     Edward  
11      4    NaN                     New York, NY          1       John  
...   ...    ...                              ...        ...        ...  
1275  NaN    NaN                              NaN          1        Leo  
1279  NaN    NaN                              NaN          1      Hulda  
1288  NaN  314.0                              NaN          1      Jakob  
1300  NaN    NaN                              NaN          1     Antoni  
1304  NaN  328.0                              NaN          1     Hileni  

[257 rows x 16 columns]

Всего таких пассажиров оказалось 257

In [36]:
old_70 = df[df['age'] > 70].shape[0]
print(f'Пассажиров старше 70 лет было {old_70} на борту')

Пассажиров старше 70 лет было 6 на борту


**Задание 5**
+ Посчитайте средний возраст среди мужчин и среди женщин.
+ Посчитайте доли выживших в различных возрастных группах (новый признак **AgeGroup**).
+ Найдите максимальную стоимость билета в каждом из ценовых классов.

In [38]:
print(f'Средний возраст мужчин {df[df["sex"] == "male"]["age"].mean():.0f}')
print(f'Средний возраст женщин {df[df["sex"] == "female"]["age"].mean():.0f}')

Средний возраст мужчин 31
Средний возраст женщин 29


In [39]:
age_groups = [1, 2, 3]

for group in age_groups:
    survived_count = df[(df['age_group'] == group) & (df['survived'] == 1)].shape[0]
    total_count = df[df['age_group'] == group].shape[0]
    survival_rate = round(survived_count / total_count, 4)
    
    print(f'Доля выживших в возрастной группе {group} составляет {survival_rate}')


Доля выживших в возрастной группе 1 составляет 0.4095
Доля выживших в возрастной группе 2 составляет 0.3663
Доля выживших в возрастной группе 3 составляет 0.2424


In [40]:
max = df.groupby('pclass')['fare'].max().reset_index()
max.columns = ['Ценовой класс','Максимальная стоимость']
max

Ценовой класс  Максимальная стоимость
0              1                512.3292
1              2                 73.5000
2              3                 69.5500

**Задание 6**\
Ответьте на предыдущие вопросы с помощью функции crosstab и метода pivot_table.

In [42]:
age_mean_crosstab = pd.crosstab(df['sex'], columns='Средний возраст', values=df['age'], aggfunc='mean')
age_mean_crosstab

col_0   Средний возраст
sex                    
female        28.687071
male          30.585233

In [43]:
age_mean_pivot = df.pivot_table(index='sex', values='age', aggfunc='mean')
age_mean_pivot

age
sex              
female  28.687071
male    30.585233

In [44]:
survival_rates_crosstab = pd.crosstab(df['age_group'], columns='Доля выживших', values=df['survived'], aggfunc='mean')
survival_rates_crosstab

col_0      Доля выживших
age_group               
1               0.409490
2               0.366337
3               0.242424

In [45]:
survival_rates_pivot = df.pivot_table(index='age_group', values='survived', aggfunc='mean')
survival_rates_pivot

survived
age_group          
1          0.409490
2          0.366337
3          0.242424

In [46]:
max_fare_crosstab = pd.crosstab(df['pclass'], columns='Максимальная стоимость билета', values=df['fare'], aggfunc='max')
max_fare_crosstab

col_0   Максимальная стоимость билета
pclass                               
1                            512.3292
2                             73.5000
3                             69.5500

In [47]:
max_fare_pivot = df.pivot_table(index='pclass', values='fare', aggfunc='max')
max_fare_pivot

fare
pclass          
1       512.3292
2        73.5000
3        69.5500